# Generated by Django 4.0.4 on 2022-04-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaz', models.CharField(max_length=255)),
                ('rus', models.CharField(max_length=255)),
                ('bagga', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaz', models.CharField(max_length=255)),
                ('rus', models.CharField(max_length=255)),
                ('bagga', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaz', models.CharField(max_length=255)),
                ('rus', models.CharField(max_length=255)),
                ('bagga', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
