# Generated by Django 4.0.4 on 2022-04-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esim', models.CharField(default='', max_length=255, verbose_name='Esimi')),
                ('teg', models.TextField(blank=True, default='', verbose_name='Tegi')),
                ('nomer', models.IntegerField(default=87777777777, verbose_name='Nomeri')),
                ('kala', models.CharField(default='', max_length=255, verbose_name='Kalasy')),
                ('email', models.EmailField(blank=True, default='@gmail.com', max_length=254, verbose_name='Elektrondyk poshta')),
                ('image', models.ImageField(blank=True, default='default value', null=True, upload_to='user_gallery', verbose_name='3*4 suret')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Kelisim')),
            ],
        ),
    ]
